# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c18949a7993b824c5f22e32a365da97835f773cdc73d3e5094bde0a24669ac00d5a151e9bf520a4e8823190a162650650ee65a59088290abf2c67e646e51a23

test:
  secret_key_base: 90533770c40fb98ae0b10abe3eb9d27a7b706aeca256e8a5197e4281b58d0b7b2be72586e81d57539185c000cab665a689ee9aba6fb59eb4d929451c9e8962ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
